dataset:
  num_classes: 2
  num_dim: 2
  source:
    class_means: [[-2.5, -1.5], [-1.0, -1.0]]
    num_instances_train: 1000
    num_instances_test: 100
    class_ratio: 0.5
    noise_sf: 0.15

  target:
    class_means: [[1.0, 1.0], [2.5, 1.5]]
    num_instances_train: 1000
    num_instances_test: 100
    class_ratio: 0.5
    noise_sf: 0.25

model:
  embedding_size: 2
  hidden_units: 7
  num_iterations: 60000
  batch_size: 80
  batch_factor: 2
  num_trials: 1
  output_path: 'results/'

loss:
  domain_weight: 1.0
  reverse_grad_scale_factor: 1.0
  classify_weight: 1.0
  triplet_weight: 1.0
  triplet_margin: 0.7
  triplet_KL_weight: 1.0
  triplet_KL_margin: 2.0
  class_dann_weight: 0.5
  entropy_weight: 0.0001